### ISSUE TITLE
Research/prototype applicant and agency feedback flow

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#1421]
## Background
After an applicant finishes filling out their form they submit it to their agency for review. Often times the agency marks questions that need clarification, have errors, etc. Those notes are sent through an email process now. 

## Solution prompt
How might we help applicants better respond to feedback given by an agency directly within eApp?

## Tasks
- [x] Review past design work on this process
- [ ] Research agency feedback capabilities within the IM (was not able to connect with IM design team, maybe this could be an action item for IM PI planning meeting?)
- [x] Iterate on wireframes/prototypes for applicant response to feedback
- [x] Create user testing script and schedule participants

**Comment by joshmfranklin** [comment]
Start of a interactive prototype located here: 
https://practical-knuth-580001.netlify.com/
