### ISSUE TITLE
Test eQIP web service submissions and automate tests

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#145]
From e-QIP-prototype-truetandem created by [pjsumm](https://github.com/pjsumm) : ryanhofdotgov/e-QIP-prototype-truetandem#2876  

As a eApp developer I want to test submitting data in all fields of the eApp online application form to the eQIP test/integration site via web service so that I can validate that the data submits without error.

Acceptance Criteria
- [ ] Create test automation design 
- [ ] 18f approval of test automation design 
- [ ] Verify all form data submits without error.  See #2850
