### ISSUE TITLE
Review STIG checklist comments

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#149]
From e-QIP-prototype-truetandem created by [pjsumm](https://github.com/pjsumm) : ryanhofdotgov/e-QIP-prototype-truetandem#2869  

As an eApp stakeholder I want to review comments on the eApp STIG checklist provided by the eApp security team and respond to the comments so that I can return updated comments to the security team for further review.

Acceptance Criteria:
- [ ] Provide responses to ~50 security team questions
- [ ] Facilitate feedback from infrastructure team
- [ ] Submit result to eApp security team

**Comment by ryanhofdotgov** [comment]
Application STIG was reviewed in its entirety in July, compliance-related issues were opened, and re-submitted back to infrastructure team.
