### ISSUE TITLE
Implement term help tips

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#265]
From e-QIP-prototype-truetandem created by [pjsumm](https://github.com/pjsumm) : ryanhofdotgov/e-QIP-prototype-truetandem#1983  

As an eApp applicant I want to see in-line assistance/help for complex terms so that I can get a better understanding of complex terms without leaving the page.

Acceptance Criteria
- [ ] Follow the design from #1871 
- [ ] Implement framework using term example from the story board
- [ ] Make framework easy to implement across the form
