### ISSUE TITLE
Applicant registration form

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#276]
From e-QIP-prototype-truetandem created by [pjsumm](https://github.com/pjsumm) : ryanhofdotgov/e-QIP-prototype-truetandem#1881  

As an eApp developer I want to create a user registration form that ensures the user registering is the user we think it is, so that they can proceed to create a user id and password on the registration form and they can use their new credential (id/password) to access the eApp form. 

Acceptance Criteria
- [ ] Follows the design in the storyboard #1878 
- [ ] Create form with following information/fields
  - [ ] Warning the user is accessing a government site 
  - [ ] First prompt user to enter email address  
  - [ ] Confirm code and email match and within validity period
  - [ ] Provide user id/password requirements
  - [ ] Prompt user to enter a user ID and password, re-prompt for password
  - [ ] In-line validation of user ID/password based on recommended requirements 
  - [ ] Submit and confirm creation of account

**Comment by ryanhofdotgov** [comment]
OBE – now handled by another NBIS component.
