### ISSUE TITLE
Create registration code

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#278]
From e-QIP-prototype-truetandem created by [pjsumm](https://github.com/pjsumm) : ryanhofdotgov/e-QIP-prototype-truetandem#1879  

As an eApp developer I want to create a service to generate and validate eApp applicant registration codes so that users can create/register their user account to access the eApp form online. 

Acceptance Criteria
- [ ] Create server-side process to generate the registration code 
- [ ] Ensure code is unique
- [ ] Time-stamp registration code validity period (need to determine how long the reg code is active)
- [ ] Associate unique registration code to the applicant's email address
- [ ] Endpoint to verify user code/email/time-stamp combination

**Comment by ryanhofdotgov** [comment]
OBE – now handled by another NBIS component.
