### ISSUE TITLE
SSN - validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#324]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1408  

Validation for Social Security Number:
- [ ] If initiated without SSN no applicant SSN allowed, NA should be checked. 
- [ ] If present SSN must match SSN used to initiate. 
- [ ] If case initiated with SSN, NA not allowed. 
- [ ] Fatal error not letting applicant proceed until SSN matches. 
- [x] Only numbers allowed.
- [ ] 999-99-9999 and 123-45-6789 are not allowed values.

<img width="797" alt="screen shot 2017-06-13 at 11 11 44 am" src="https://user-images.githubusercontent.com/19935974/27089672-18eee948-5029-11e7-9818-5554c2fc2f97.png">
